### ISSUE TITLE
ffmpeg url not available anymore

### ISSUE THREAD

**Issue by rbalaine** [jonathanong/heroku-buildpack-ffmpeg-latest#12]
Hello,

In file /bin/compile, the ffmpeg tar file url in DOWNLOAD_URL is not available anymore (404 on https://www.johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz). So this heroku buildpack can't be used anymore.

Regards,
Romain

**Comment by HeadTriXz** [comment]
I still got this as a build pack but it stopped working...

**Comment by TAMU-MIRC-SOFTWARE** [comment]
It appears as if he changed the URL on his website without updating this repo. In the compile file it still has the old URL. Not sure which one to choose from. 

https://www.johnvansickle.com/ffmpeg/

**Comment by TAMU-MIRC-SOFTWARE** [comment]
Howdy all!

I made a fork and I believe it works. Use this instead until this repo issue is resolved. 

https://github.com/TAMU-MIRC-SOFTWARE/heroku-buildpack-ffmpeg-latest.git

**Comment by TAMU-MIRC-SOFTWARE** [comment]
The fix has been merged now. It's using the AMD 64bit file. Hopefully that works for everyone. If not just for your own and replace the DOWNLOAD_URL with the one you need at https://www.johnvansickle.com/ffmpeg/.
