### ISSUE TITLE
how to call out the function (I am a newbie)

### ISSUE THREAD

**Issue by khoo2002** [jonathanong/heroku-buildpack-ffmpeg-latest#15]
import ffmpeg
input =ffmpeg.input('xx.mp4')
output = ffmpeg.output(output,'xx.mp3',f='mp3',vn=True)
ffmpeg.run(output)
I fail to use this code
can you give an example 
pls give an example

**Comment by jonathanong** [comment]
see https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest/issues/16
