### ISSUE TITLE
Where is FFMPEG file in Heroku

### ISSUE THREAD

**Issue by arisprung18** [jonathanong/heroku-buildpack-ffmpeg-latest#16]
I am directing the FFMPEG to my local file when running on my local computer.
 
```java
FFmpeg ffmpeg = new FFmpeg("/usr/local/Cellar/ffmpeg/4.2.1_2/bin/ffmpeg");
```

However when I deploy to Heroku where should I direct the FFMPEG initialization?

**Comment by spookyUnknownUser** [comment]
AFAIK, with this buildpack, `ffmpeg` becomes available as an environmental varible, meaning you should be able to use it anywhere wihtout specifiying the path an just writing `ffmpeg`.

So the path would just be `ffmpeg` and your code would become: 
```java
FFmpeg ffmpeg = new FFmpeg("ffmpeg");
```

But I could be wrong 😥

**Comment by jonathanong** [comment]
on heroku, it's in your `$PATH`, so you just have to call `ffmpeg` from the CLI.

**Comment by jonathanong** [comment]
which i'm assuming what @spookyUnknownUser's code does
