### ISSUE TITLE
Breaking for me during build

### ISSUE THREAD

**Issue by mayeaux** [jonathanong/heroku-buildpack-ffmpeg-latest#2]
<img width="719" alt="screen shot 2017-08-27 at 8 24 54 pm" src="https://user-images.githubusercontent.com/7200471/29758116-d7802c06-8b65-11e7-98aa-f4d221f35416.png">

**Comment by adamstorr** [comment]
+1

**Comment by valindah** [comment]
The owner of the web site on which the "tar" archive is located has not renewed its https certificate.

**Comment by mrmayfield** [comment]
So what can we do? I found this buildpack:

https://github.com/shunjikonishi/heroku-buildpack-ffmpeg

But the ffmpeg binary doesn't have the codecs I need. Anyone want to help me with that?

**Comment by valindah** [comment]
I cloned this depot and just added --insecure to the curl command, I hope this correction will be made on this repository.

https://github.com/valindah/heroku-buildpack-ffmpeg-latest.git

**Comment by jonathanong** [comment]
aw man... yeah just use his fork until the owner has fixed their HTTPS certificate. i don't really want to commit an `--insecure` command

**Comment by jonathanong** [comment]
unless you all think i should...

**Comment by valindah** [comment]
I also prefer not to use insecure, it's a temporary use for me

**Comment by jonathanong** [comment]
too bad his site redirects from HTTP to HTTPS. i have no idea how to contact him

**Comment by valindah** [comment]
I don't have the same mistake as earlier, I think he noticed the problem

**Comment by valindah** [comment]
I found his email with the google cache : john dot vansickle at gmail dot com

**Comment by mrmayfield** [comment]
I still get an HTTP insecure error but I'm using your fork.

Can't we host these binaries on GH or some big platform as opposed to some random guy's website?

**Comment by valindah** [comment]
Unfortunately no, this guy is directly referenced by the official website of ffmpeg as Linux Static Builds

**Comment by mrmayfield** [comment]
L O L 
Can we get someone who knows to update their certs on time? 😅 This blew up prod for me... :|

**Comment by valindah** [comment]
The certificate is restored yeah!

**Comment by AkechiShiro** [comment]
For me it began to do the same errors again with the tar archive, I don't think the certificate is dead but here is [an alternative](https://github.com/ello/heroku-buildpack-apt-ffmpeg) that worked for me.

**Comment by bgirschig** [comment]
It looks like johnvansickle simply shut it down, now. Can anyone confirm ?
![image](https://user-images.githubusercontent.com/6248734/40201178-a1bd0142-5a1e-11e8-9d37-dbe3e0573c74.png)

Side question: it it possible to do something like apt-get install ffmpeg in a buildpack ? I suppose not, but what would a solution ?
Maybe someone still has a recent build saved somewhere?

**Comment by jonathanong** [comment]
https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest/issues/4
