### ISSUE TITLE
Does this have x264lib support?

### ISSUE THREAD

**Issue by kuletxcore** [jonathanong/heroku-buildpack-ffmpeg-latest#22]
I was just wondering if this has support for libx264-dev or not. If not, then this builfpack should get support for it.

Thank you!

**Comment by jonathanong** [comment]
@kuletxcore can you ask the person who creates the static builds https://www.johnvansickle.com/ffmpeg/

**Comment by jonathanong** [comment]
looks like it https://johnvansickle.com/ffmpeg/release-readme.txt

**Comment by kuletxcore** [comment]
> looks like it https://johnvansickle.com/ffmpeg/release-readme.txt

Thank you! :)
