### ISSUE TITLE
Error: FFmpeg/avconv not found! Error

### ISSUE THREAD

**Issue by gabrielgnd1** [jonathanong/heroku-buildpack-ffmpeg-latest#25]
I don't really know how to use buildpack so I paste it to my command. Help me. THis error same as before I installed ffmpeg in my first musicbot

**Comment by khoo2002** [comment]
Can you show your code？

**Comment by gabrielgnd1** [comment]
Im sorry, I just added the buildpack and its perfectly fine now. I didnt
know setting exist lol. Sorry

Pada tanggal Rab, 26 Agt 2020 21.54, khoo2002 <notifications@github.com>
menulis:
