### ISSUE TITLE
Propagate archive errors to make buildpack properly fail

### ISSUE THREAD

**Issue by SleeplessByte** [jonathanong/heroku-buildpack-ffmpeg-latest#27]
Hi there,

Low priority issue; only experience this about once every 100 builds, if that.

## The issue

Sometimes, something goes wrong on the heroku end with unpacking or downloading the archive:

```text
remote: -----> Install ffmpeg
remote:        DOWNLOAD_URL =  https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
remote: xz: (stdin): Unexpected end of input
remote: tar: Unexpected EOF in archive
remote: tar: Unexpected EOF in archive
remote: tar: Error is not recoverable: exiting now
remote:        exporting PATH
```

Unfortunately the error doesn't _propagate_, so you're left with a dyno without ffmpeg.

## Expected behaviour

It either checks if ffmpeg now exists, or it propagates download/tar/xz errors, so that the buildpack fails and therefore the entire build fails.

## Workaround

There is none, other than re-deploying with a new commit [empty or not] added. That's the real culprit. It means that even if we detect it (which is easy to do, by testing if `ffmpeg` exists), retrying is non-trivial, with a few minutes of dynos in a corrupt state.

**Comment by jrdioko** [comment]
We also just ran into this. To avoid "a few minutes of dynos in a corrupt state", just a `heroku rollback` should work. But this seems like a fairly serious issue as it allows these deploys to succeed with no indication something is wrong (other than a few messages in the log).

**Comment by edmorley** [comment]
PR #39 will resolve this.
