### ISSUE TITLE
Update usage instructions

### ISSUE THREAD

**Issue by edmorley** [jonathanong/heroku-buildpack-ffmpeg-latest#28]
Hi :-)

On https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest#usage it mentions adding the buildpack to the `.buildpacks` file, however this method only works with the deprecated multi buildpack:
https://github.com/heroku/heroku-buildpack-multi

Would it be possible to remove that reference, to prevent confusion?

Also for this usage example:

> heroku buildpacks:add https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git

I would recommend changing it to `heroku buildpacks:add --index 1`, so the buildpack is added before the existing buildpacks, since:
* If those buildpacks need ffmpeg, they'll need it to be installed first
* the buildpacks API treats the last buildpack in the list as the "primary" buildpack for the release metadata step (which sets new app procfile entries and addons), so it's best if supplementary buildpacks are not last in the list

Many thanks :-)

**Comment by jonathanong** [comment]
pull request welcomed :) 

i am not currently using this buildpack so i don't know what's the best, current way of installing it

**Comment by edmorley** [comment]
@jonathanong thank you - I've opened #35 :-)
