### ISSUE TITLE
Not really an issue but need to ask this

### ISSUE THREAD

**Issue by dev-shah-2204** [jonathanong/heroku-buildpack-ffmpeg-latest#51]
Where do I set the variable `FFMPEG_DOWNLOAD_URL`? In my config vars?

I'm deploying a python app.

**Comment by jonathanong** [comment]
environment variables

**Comment by dev-shah-2204** [comment]
Yea I tried that, it didn't work. What do I do?

**Comment by dev-shah-2204** [comment]
Never mind, I didn't realise my app was up. I messed up the authentication token. Works perfectly!
