### ISSUE TITLE
SSL certificate www.johnvansickle.com expired

### ISSUE THREAD

**Issue by mikehanssen** [jonathanong/heroku-buildpack-ffmpeg-latest#6]
Seems like the SSL certificate of the website hosting the ffmpeg release has expired today.

**Comment by maaz23451** [comment]
The buildpack(ffmpeg) doesn't work , how do i solve this ?

**Comment by Kjwon15** [comment]
Replace
`curl -L --silent $DOWNLOAD_URL | tar xJ --strip-components=1`
to
`curl -kL --silent $DOWNLOAD_URL | tar xJ --strip-components=1`
to fix temporarily.

**Comment by mikehanssen** [comment]
As the SSL certificate has been renewed I'll close this issue.

**Comment by adamjpeterson** [comment]
I think SSL expired again?
