### ISSUE TITLE
Troubles with buildpack on Heroku

### ISSUE THREAD

**Issue by merive** [jonathanong/heroku-buildpack-ffmpeg-latest#65]
Yesterday, I found what my discord bot music feature isn't working. I got the next error in Heroku logs: `ffmpeg process 12 successfully terminated with return code of -11`. How to fix this error and what it's mean? Also I test the bot on my local machine and all works okay.
UPD: I use Heroku-22 stack

**Comment by JD-Durant** [comment]
This Buildpack doesn't support Heroku-22 stack, I had similar issues. Revert it back to Heroku-20 Stack and all should be good c:

**Comment by IAMSDR** [comment]
still same error in Heroku-20 stack
**ERROR: ffmpeg exited with code -11**
i'm using ffmpeg for yt-dlp merging
